package runit

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"shim-systemctl/pkg/cgroups"
	"shim-systemctl/pkg/units"
	"strings"
	"time"
)

type Manager struct {
	ServiceDir    string
	EnableDir     string
	CgroupManager *cgroups.Manager
}

func getEnv(key, defaultValue string) string {
	value := os.Getenv(key)
	if value == "" {
		return defaultValue
	}
	return value
}

func NewManager() *Manager {
	enableDir := getEnv("RUNIT_SERVICE_DIR", "")
	if enableDir == "" {
		// Detect Artix/Void style /run/runit/service
		if _, err := os.Stat("/run/runit/service"); err == nil {
			enableDir = "/run/runit/service"
		} else {
			enableDir = "/var/service"
		}
	}

	return &Manager{
		ServiceDir:    getEnv("RUNIT_SV_DIR", "/etc/runit/sv"),
		EnableDir:     enableDir,
		CgroupManager: cgroups.NewManager(),
	}
}

func (m *Manager) GenerateRunScript(name string, unit *units.Unit) string {
	var script strings.Builder
	script.WriteString("#!/bin/sh\n")
	script.WriteString("# Generated by SINS - SINS Is Not Systemd\n\n")

	// Cgroup migration
	script.WriteString(fmt.Sprintf("mkdir -p /sys/fs/cgroup/sins/%s\n", name))
	script.WriteString(fmt.Sprintf("echo $$ > /sys/fs/cgroup/sins/%s/cgroup.procs\n\n", name))

	// Handle dependencies
	after := unit.GetAll("Unit", "After")
	requires := unit.GetAll("Unit", "Requires")
	for _, dep := range append(after, requires...) {
		if strings.HasSuffix(dep, ".target") {
			continue
		}
		depName := strings.TrimSuffix(dep, ".service")
		script.WriteString(fmt.Sprintf("sv check %s || exit 1\n", depName))
	}

	execStart := unit.Get("Service", "ExecStart")
	user := unit.Get("Service", "User")
	workDir := unit.Get("Service", "WorkingDirectory")

	if workDir != "" {
		script.WriteString(fmt.Sprintf("cd %s\n", workDir))
	}

	script.WriteString("exec ")
	if user != "" {
		script.WriteString(fmt.Sprintf("chpst -u %s ", user))
	}
	
	if _, err := os.Stat(filepath.Join(m.ServiceDir, name, "env")); err == nil {
		script.WriteString("chpst -e ./env ")
	}
	
	script.WriteString(execStart + "\n")

	return script.String()
}

func (m *Manager) SetupService(name string, unit *units.Unit) error {
	svPath := filepath.Join(m.ServiceDir, name)
	if err := os.MkdirAll(svPath, 0755); err != nil {
		return fmt.Errorf("failed to create service directory: %w", err)
	}

	if err := m.SetupEnv(svPath, unit); err != nil {
		return err
	}

	limits := map[string]string{
		"MemoryMax": unit.Get("Service", "MemoryMax"),
		"CPUQuota":  unit.Get("Service", "CPUQuota"),
	}
	m.CgroupManager.SetupServiceCgroup(name, limits)

	if err := m.SetupLog(svPath); err != nil {
		return err
	}

	runScript := m.GenerateRunScript(name, unit)
	runPath := filepath.Join(svPath, "run")
	return os.WriteFile(runPath, []byte(runScript), 0755)
}

func (m *Manager) SetupEnv(svPath string, unit *units.Unit) error {
	envs := unit.GetAll("Service", "Environment")
	if len(envs) == 0 {
		return nil
	}

	envPath := filepath.Join(svPath, "env")
	if err := os.MkdirAll(envPath, 0755); err != nil {
		return err
	}

	for _, env := range envs {
		env = strings.Trim(env, "\"")
		parts := strings.SplitN(env, "=", 2)
		if len(parts) == 2 {
			k, v := parts[0], strings.TrimSpace(parts[1])
			if err := os.WriteFile(filepath.Join(envPath, k), []byte(v), 0644); err != nil {
				return err
			}
		}
	}
	return nil
}

func (m *Manager) SetupLog(svPath string) error {
	logPath := filepath.Join(svPath, "log")
	if err := os.MkdirAll(logPath, 0755); err != nil {
		return err
	}

	logRunScript := "#!/bin/sh\nexec svlogd -tt ./main\n"
	if err := os.WriteFile(filepath.Join(logPath, "run"), []byte(logRunScript), 0755); err != nil {
		return err
	}

	return os.MkdirAll(filepath.Join(logPath, "main"), 0755)
}

func (m *Manager) EnableService(name string) error {
	svPath := filepath.Join(m.ServiceDir, name)
	enablePath := filepath.Join(m.EnableDir, name)
	
	if err := os.MkdirAll(m.EnableDir, 0755); err != nil {
		return fmt.Errorf("failed to create enable directory: %w", err)
	}

	if _, err := os.Lstat(enablePath); err == nil {
		return nil
	}

	return os.Symlink(svPath, enablePath)
}

func (m *Manager) DisableService(name string) error {
	enablePath := filepath.Join(m.EnableDir, name)
	if _, err := os.Lstat(enablePath); err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}
	return os.Remove(enablePath)
}

// WaitForService waits for runit to pick up the service and enter 'run' state
func (m *Manager) WaitForService(name string, timeout int) error {
	supervisePath := filepath.Join(m.EnableDir, name, "supervise")
	fmt.Printf("SINS: Waiting for %s to enter 'run' state... (target: %s)\n", name, supervisePath)
	
	for i := 0; i < timeout*10; i++ {
		// First check for supervise directory
		if _, err := os.Stat(supervisePath); err == nil {
			// Then check status via sv
			cmd := exec.Command("sv", "status", name)
			output, _ := cmd.CombinedOutput()
			if strings.HasPrefix(string(output), "run:") {
				return nil
			}
		}
		time.Sleep(100 * time.Millisecond)
	}
	return fmt.Errorf("timeout waiting for %s to become active", name)
}
