package runit

import (
	"fmt"
	"os"
	"path/filepath"
	"shim-systemctl/pkg/cgroups"
	"shim-systemctl/pkg/units"
	"strings"
	"time"
)

type Manager struct {
	ServiceDir    string
	EnableDir     string
	CgroupManager *cgroups.Manager
}

func getEnv(key, defaultValue string) string {
	value := os.Getenv(key)
	if value == "" {
		return defaultValue
	}
	return value
}

func NewManager() *Manager {
	enableDir := getEnv("RUNIT_SERVICE_DIR", "")
	if enableDir == "" {
		// Detect Artix/Void style /run/runit/service
		if _, err := os.Stat("/run/runit/service"); err == nil {
			enableDir = "/run/runit/service"
		} else {
			enableDir = "/var/service"
		}
	}

	return &Manager{
		ServiceDir:    getEnv("RUNIT_SV_DIR", "/etc/runit/sv"),
		EnableDir:     enableDir,
		CgroupManager: cgroups.NewManager(),
	}
}

func (m *Manager) GenerateRunScript(name string, unit *units.Unit) string {
	var script strings.Builder
	script.WriteString("#!/bin/sh\n")
	script.WriteString("# Generated by SINS - SINS Is Not Systemd\n")
	script.WriteString("exec 2>&1\n\n")

	// Cgroup migration
	script.WriteString(fmt.Sprintf("mkdir -p /sys/fs/cgroup/sins/%s\n", name))
	script.WriteString(fmt.Sprintf("echo $$ > /sys/fs/cgroup/sins/%s/cgroup.procs\n\n", name))

	// Handle ExecStartPre
	execPre := unit.GetAll("Service", "ExecStartPre")
	for _, cmd := range execPre {
		// Remove leading '-' which means ignore error in systemd
		ignoreError := strings.HasPrefix(cmd, "-")
		if ignoreError {
			cmd = cmd[1:]
		}
		script.WriteString(fmt.Sprintf("echo \"Running ExecStartPre: %s\"\n", cmd))
		if ignoreError {
			script.WriteString(fmt.Sprintf("%s || true\n", cmd))
		} else {
			script.WriteString(fmt.Sprintf("%s || exit 1\n", cmd))
		}
	}

	// Handle dependencies
	after := unit.GetAll("Unit", "After")
	requires := unit.GetAll("Unit", "Requires")
	for _, depLine := range append(after, requires...) {
		for _, dep := range strings.Fields(depLine) {
			if strings.HasSuffix(dep, ".target") || strings.HasSuffix(dep, ".device") || strings.HasSuffix(dep, ".mount") {
				continue
			}
			depName := dep
			depName = strings.TrimSuffix(depName, ".service")
			depName = strings.TrimSuffix(depName, ".socket")
			depName = strings.TrimSuffix(depName, ".timer")
			// Only check dependencies that exist in runit
			if _, err := os.Stat(filepath.Join(m.ServiceDir, depName)); err == nil {
				script.WriteString(fmt.Sprintf("sv check %s || exit 1\n", depName))
			}
		}
	}

	execStart := unit.Get("Service", "ExecStart")
	user := unit.Get("Service", "User")
	workDir := unit.Get("Service", "WorkingDirectory")

	if workDir != "" {
		script.WriteString(fmt.Sprintf("cd %s\n", workDir))
	}

	serviceType := unit.Get("Service", "Type")
	pidFile := unit.Get("Service", "PIDFile")

	if serviceType == "notify" {
		script.WriteString("export NOTIFY_SOCKET=/run/systemd/notify\n")
	}

	if serviceType == "forking" {
		script.WriteString("trap 'kill -TERM $PID 2>/dev/null; exit 0' TERM INT\n")
		script.WriteString(execStart + "\n")
		if pidFile != "" {
			script.WriteString(fmt.Sprintf("\n# Wait for PID file and monitor forking process\n"))
			script.WriteString(fmt.Sprintf("for i in $(seq 1 30); do [ -f %s ] && break; sleep 0.5; done\n", pidFile))
			script.WriteString(fmt.Sprintf("PID=$(cat %s 2>/dev/null)\n", pidFile))
			script.WriteString("if [ -n \"$PID\" ]; then\n")
			script.WriteString(fmt.Sprintf("  echo \"Monitoring forking PID $PID from %s\"\n", pidFile))
			script.WriteString("  while kill -0 $PID 2>/dev/null; do sleep 2; done\n")
			script.WriteString("fi\n")
		} else {
			// Fallback: if no PIDFile, we can only hope it stays in foreground or we just exit
			script.WriteString("# Warning: Type=forking without PIDFile. Runit might not track this correctly.\n")
		}
	} else {
		script.WriteString("exec ")
		if user != "" {
			script.WriteString(fmt.Sprintf("chpst -u %s ", user))
		}

		if _, err := os.Stat(filepath.Join(m.ServiceDir, name, "env")); err == nil {
			script.WriteString(fmt.Sprintf("chpst -e %s ", filepath.Join(m.ServiceDir, name, "env")))
		}

		script.WriteString(execStart + "\n")
	}

	return script.String()
}

func (m *Manager) GenerateSocketRunScript(name string, unit *units.Unit) string {
	var script strings.Builder
	script.WriteString("#!/bin/sh\n")
	script.WriteString("# Generated by SINS - Socket Activator\n")
	script.WriteString("exec 2>&1\n\n")

	systemctlPath := getEnv("SYSTEMCTL_PATH", "/usr/bin/systemctl")
	script.WriteString(fmt.Sprintf("exec sins-sockets %s %s\n", unit.Path, systemctlPath))

	return script.String()
}

func (m *Manager) SetupService(name string, unit *units.Unit) error {
	svPath := filepath.Join(m.ServiceDir, name)
	if err := os.MkdirAll(svPath, 0755); err != nil {
		return fmt.Errorf("failed to create service directory: %w", err)
	}

	if err := m.SetupEnv(svPath, unit); err != nil {
		return err
	}

	limits := map[string]string{
		"MemoryMax": unit.Get("Service", "MemoryMax"),
		"CPUQuota":  unit.Get("Service", "CPUQuota"),
	}
	m.CgroupManager.SetupServiceCgroup(name, limits)

	if err := m.SetupLog(svPath); err != nil {
		return err
	}

	var runScript string
	if strings.HasSuffix(unit.Path, ".socket") {
		runScript = m.GenerateSocketRunScript(name, unit)
	} else {
		runScript = m.GenerateRunScript(name, unit)
	}
	
	runPath := filepath.Join(svPath, "run")
	return os.WriteFile(runPath, []byte(runScript), 0755)
}

func (m *Manager) SetupEnv(svPath string, unit *units.Unit) error {
	envs := unit.GetAll("Service", "Environment")
	envFiles := unit.GetAll("Service", "EnvironmentFile")
	
	if len(envs) == 0 && len(envFiles) == 0 {
		return nil
	}

	envPath := filepath.Join(svPath, "env")
	if err := os.MkdirAll(envPath, 0755); err != nil {
		return err
	}

	// Helper to write env file
	writeEnv := func(k, v string) error {
		return os.WriteFile(filepath.Join(envPath, k), []byte(v), 0644)
	}

	// 1. Process EnvironmentFile
	for _, file := range envFiles {
		ignoreMissing := strings.HasPrefix(file, "-")
		if ignoreMissing {
			file = file[1:]
		}
		
		data, err := os.ReadFile(file)
		if err != nil {
			if ignoreMissing {
				continue
			}
			return fmt.Errorf("failed to read EnvironmentFile %s: %w", file, err)
		}
		
		lines := strings.Split(string(data), "\n")
		for _, line := range lines {
			line = strings.TrimSpace(line)
			if line == "" || strings.HasPrefix(line, "#") {
				continue
			}
			parts := strings.SplitN(line, "=", 2)
			if len(parts) == 2 {
				writeEnv(parts[0], strings.Trim(parts[1], "\"'"))
			}
		}
	}

	// 2. Process Environment (overrides files)
	for _, env := range envs {
		env = strings.Trim(env, "\"")
		parts := strings.SplitN(env, "=", 2)
		if len(parts) == 2 {
			writeEnv(parts[0], strings.TrimSpace(parts[1]))
		}
	}
	return nil
}

func (m *Manager) SetupLog(svPath string) error {
	logPath := filepath.Join(svPath, "log")
	if err := os.MkdirAll(logPath, 0755); err != nil {
		return err
	}

	logRunScript := "#!/bin/sh\nexec svlogd -tt ./main\n"
	if err := os.WriteFile(filepath.Join(logPath, "run"), []byte(logRunScript), 0755); err != nil {
		return err
	}

	return os.MkdirAll(filepath.Join(logPath, "main"), 0755)
}

func (m *Manager) EnableService(name string) error {
	svPath := filepath.Join(m.ServiceDir, name)
	enablePath := filepath.Join(m.EnableDir, name)
	
	if err := os.MkdirAll(m.EnableDir, 0755); err != nil {
		return fmt.Errorf("failed to create enable directory: %w", err)
	}

	// Always recreate the link to ensure it's not broken and points to the right place
	os.Remove(enablePath)
	return os.Symlink(svPath, enablePath)
}

func (m *Manager) DisableService(name string) error {
	enablePath := filepath.Join(m.EnableDir, name)
	if _, err := os.Lstat(enablePath); err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}
	return os.Remove(enablePath)
}

// WaitForService waits for runit to pick up the service (supervise directory creation)
func (m *Manager) WaitForService(name string, timeout int) error {
	supervisePath := filepath.Join(m.EnableDir, name, "supervise")
	fmt.Printf("Waiting for runsv to initialize %s... (polling %s)\n", name, supervisePath)
	
	// Poll every 100ms for better responsiveness
	for i := 0; i < timeout*10; i++ {
		if _, err := os.Stat(supervisePath); err == nil {
			return nil
		}
		time.Sleep(100 * time.Millisecond)
	}
	return fmt.Errorf("timeout waiting for runsv to start for service %s", name)
}
